### ISSUE TITLE
Length of the row

### ISSUE THREAD

**Issue by Sector347** [fgardt/factorio-spritter#29]
Hello! Could you please add ability to specify number of sprites in the row when generating spritesheet. By default it generates exactly 15 sprites in the row. But character animations, for instance, require 22 sprites in a row. That would be much appreciated.

**Comment by fgardt** [comment]
Could you point me to the prototype API docs of where you want to use that exactly?
Would help a lot to understand what capabilities are needed here :)

**Comment by fgardt** [comment]
Closing due to missing details. Afaik the generated lua output should contain everything needed to build any wanted graphics type.
